# Generated by Django 4.0.6 on 2022-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('date_creation', models.TimeField(auto_now_add=True)),
                ('sequence', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
