# Generated by Django 4.0.6 on 2022-10-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='Izdomain',
        ),
        migrations.DeleteModel(
            name='Izpart',
        ),
        migrations.DeleteModel(
            name='Linker',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Receptor',
        ),
        migrations.DeleteModel(
            name='Reviewed',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='Tmpart',
        ),
    ]
