# Generated by Django 4.0.6 on 2022-10-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_account_delete_car_delete_djangomigrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_functionality', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Izdomain',
            fields=[
                ('izdomain_id', models.AutoField(primary_key=True, serialize=False)),
                ('izdomain_functionality', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'izdomain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Izpart',
            fields=[
                ('izpart_id', models.AutoField(primary_key=True, serialize=False)),
                ('izpart_functionality', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'izpart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('linker_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'linker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('journal', models.CharField(blank=True, max_length=64, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('receptor_id', models.AutoField(primary_key=True, serialize=False)),
                ('receptor_functionality', models.TextField(blank=True, null=True)),
                ('receptor_needslinker', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewed',
            fields=[
                ('reviewed_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reviewed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_length', models.IntegerField()),
                ('seq_sequence', models.TextField()),
                ('seq_annotation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmpart',
            fields=[
                ('tmpart_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tmpart',
                'managed': False,
            },
        ),
    ]
