# Generated by Django 4.0.6 on 2022-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_1', models.TextField(blank=True, null=True)),
                ('debug_2', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debug_table',
                'managed': False,
            },
        ),
    ]
